language: minimal

services:
  - docker

branches:
  only:
    - master
    - develop

install:
  - docker build --target build -t dockerized-restinio/build .
  - docker build -t dockerized-restinio/runtime .
  - docker run -d -p 8080:8080 --name restinio dockerized-restinio/runtime

script:
  - docker ps | grep -q restinio
  - curl -X GET localhost:8080/ready